
plugins {
    id 'jacoco'
}

jacoco {
    toolVersion = "0.8.13"
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        csv.required = false
        html.required = true
    }
}

dependencies {
    implementation project(':usecase')
    implementation project(':model')

    implementation 'org.springframework:spring-context'
    implementation 'org.springframework.boot:spring-boot-starter-data-r2dbc'
    implementation 'org.postgresql:r2dbc-postgresql'

    implementation 'org.springframework.security:spring-security-crypto'

    implementation 'org.reactivecommons.utils:object-mapper-api:0.1.0'

    testImplementation 'org.reactivecommons.utils:object-mapper:0.1.0'
    implementation("org.mapstruct:mapstruct:1.6.3")
}




