server:
  port: 8080

spring:
  application:
    name: "service-users"


adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "crediya_users_db"
    schema: "public"
    username: "user"
    password: "password"


cors:
  allowed-origins: '*'