server:
  port: 8080

spring:
  application:
    name: "service-users"

data:
  r2dbc:
    repositories:
      enabled: true

adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "crediya_users_db"
    schema: "public"
    username: "root"
    password: "root"

cors:
  allowed-origins: "*"

springdoc:
  packages-to-scan: co.com.powerup.api
  paths-to-match: /api/v1/**
  webflux:
    core:
      fn:
        enabled: true
  api-docs:
    enabled: true
  show-actuator: true

logging:
  level:
    org.springframework.r2dbc.connection: DEBUG
    io.r2dbc.postgresql: DEBUG